Title: Logan Racz
#logo: assets/img
decription: A motivated problem solver eager to develop advanced data science skills to drive impactful change through data-driven insights.
show_downloads: true
theme: jekyll-theme-minimal
