Title: Logan Racz
#logo: assets/img
decription: I'm a graduate student in Data Science with a passion for turning data into actionable insights. My work spans statistical modeling, machine learning, and data visualization, with a focus on solving real-world problems. This site highlights projects that demonstrate my technical skills, analytical thinking, and commitment to using data for impact. I'm actively seeking opportunities to apply these strengths in a professional setting.
show_downloads:true
theme: jekyll-theme-minimal
